//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Members = new HashSet<Member>();
            this.Reservees = new HashSet<Reservee>();
        }
    
        public int ID { get; set; }
        public int RoomID { get; set; }
        public int ScheduleID { get; set; }
        public string StudentNumber { get; set; }
        public string Program { get; set; }
        public string Purpose { get; set; }
        public System.DateTime BookingDate { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<int> ApprovedByUserID { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
        public Nullable<int> CancelledByUserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Room Room { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Reservee> Reservees { get; set; }
    }
}
