//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public int BookingID { get; set; }

        [Required]
        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        public virtual Booking Booking { get; set; }
    }
}