//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public RoleMaster()
        {
            this.UserRolesMappings = new HashSet<UserRolesMapping>();
        }
    
        public int ID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<UserRolesMapping> UserRolesMappings { get; set; }
    }
}
