//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRolesMappings = new HashSet<UserRolesMapping>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public string Email { get; set; }
        public string UserPassword { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<System.DateTime> DateArchived { get; set; }
    
        public virtual ICollection<UserRolesMapping> UserRolesMappings { get; set; }
    }
}
